version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports: 
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "create-costumer:1:1, find-all-costumer:1:1, update-customer:1:1, delete-customer:1:1, create-product:1:1, find-all-product:1:1, create-order:1:1, find-all-order:1:1"
      KAFKA_ADVERTISED_PORT: 9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=ordering
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
  ordering-system:
    build: ./ordering-system
    command: yarn start
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/ordering-system
  order:
    build: ./order
    command: yarn start
    volumes:
      - .:/usr/order
  customer:
    build: ./customer
    command: yarn start
    volumes:
      - .:/usr/customer
  product-orders:
    build: ./product-orders
    command: yarn start
    volumes:
      - .:/usr/product-orders